version:                  "2"
checks:
  return-statements:
    config:
      threshold:          5
  method-lines:
    config:
      threshold:          30
  similar-code:
    config:
      threshold:          85
  identical-code:
    config:
      threshold:          45
  method-complexity:
    config:
      threshold:          10
  argument-count:
    config:
      threshold:          5
plugins:
  duplication:
    enabled:              true
    checks:
      Similar Code:
        enabled:          true
    config:
      languages:
        javascript:
          mass_threshold: 45
  fixme:
    enabled:              true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- node_modules/
- coverage/
- dist/
- codeclimate.html
