version: "2"
checks:
  return-statements:
    config:
      threshold: 5
  method-lines:
    config:
      threshold: 30
  similar-code:
    config:
      threshold: 80
  identical-code:
    config:
      threshold: 45
  method-complexity:
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 300
plugins:
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 45
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.ts"
    - "**.tsx"
exclude_paths:
  - test/
  - node_modules/
  - coverage/
  - dist/
  - codeclimate.html
