yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules" # Required for webpack. Otherwise, it continuously asks about CLI but doesn't install it
enableScripts: false # Otherwise, Zero Install method might not work.
